### ISSUE TITLE
LowCmd.idl文件是怎么编译的？

### ISSUE THREAD

**Issue by tokamakz** [BoosterRobotics/booster_robotics_sdk#2]
https://github.com/BoosterRobotics/booster_robotics_sdk/blob/main/include/booster/idl/b1/LowCmd.h

使用fastddsgen LowCmd.idl生成的文件有LowCmd.h和LowCmdPubSubTypes.h两个文件。

贵公司是将这两个文件合成了一个吗？

可否提供下fastddsgen的编译命令

**Comment by wyyleo** [comment]
是的，我们实现了一个工具，基于 fastddsgen 将 dds 文件合并了
